<?php

    class HexaImageTest extends PHPUnit\Framework\TestCase
    {
        protected static $TestClass;

        public function setUp()
        {
            //setup
        }


        /**
         * @dataProvider providerPath
         */
        public function testHexa($file, $path, $retValue)
        {
            ob_start();
            $return = \xtodx\HexaImage\HexaImage::getImage($file, $path);
            if ($return == $retValue) {
                $this->assertTrue(true, $return);
            } else {
                $this->assertFalse(false, $return);
            }
            ob_end_clean();
        }

        public function providerPath()
        {
            return [
                "okay" => [
                    "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
                    "/test/",
                    "/test/googlelogo_color_272x92dp.png"
                ],
                "directory" => [
                    "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
                    "/hexawhatsup/",
                    "/hexawhatsup/googlelogo_color_272x92dp.png"
                ],
                "exist" => [
                    "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color.jpg",
                    "/test/",
                    "/test/googlelogo_color_272x92dp.jpg"
                ],
                "extension" => [
                    "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.hexa",
                    "/test/",
                    "/test/googlelogo_color_272x92dp.hexa"
                ],
            ];
        }

        public function tearDown()/* The :void return type declaration that should be here would cause a BC issue */
        {
            parent::tearDown(); // TODO: Change the autogenerated stub
        }
    }